import fs from 'fs';
import path from 'path';

const ROOT_DIR = process.cwd();
const PUBLIC_DIR = path.join(ROOT_DIR, 'public');

// Map of folder codes to category IDs
const CATEGORY_MAP = {
  '01': 'svadbene',
  '02': 'xl-buketi',
  '03': 'buketi',
  '04': 'korpe',
  '05': 'box',
  '06': '101-ruza',
  '07': 'rodjendani',
  '08': 'events',
  '09': 'slatki',
  '10': 'kinder'
};

const CATEGORIES_TO_DISTRIBUTE = ['02', '03', '04', '06', '07', '08', '09', '10'];

function ensureDir(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

function sync() {
  console.log('--- Starting image sync and categorization ---');

  // Ensure all public directories 01-10 exist
  Object.keys(CATEGORY_MAP).forEach(folder => {
    ensureDir(path.join(PUBLIC_DIR, folder));
  });

  // 1. Scan public directory for uploaded images
  const publicFiles = fs.readdirSync(PUBLIC_DIR);
  const imageExtensions = ['.jpg', '.jpeg', '.png', '.heic', '.webp'];

  const uploadedImages = publicFiles.filter(file => {
    const ext = path.extname(file).toLowerCase();
    const isFile = fs.statSync(path.join(PUBLIC_DIR, file)).isFile();
    return isFile && imageExtensions.includes(ext);
  });

  console.log(`Found ${uploadedImages.length} images in the public directory.`);

  let distributedIndex = 0;

  uploadedImages.forEach(file => {
    const srcPath = path.join(PUBLIC_DIR, file);
    const fileNameLower = file.toLowerCase();

    let targetFolder = '';

    if (fileNameLower.includes('box')) {
      targetFolder = '05'; // Box category
    } else if (fileNameLower.includes('svadben') || fileNameLower.includes('svadba') || fileNameLower.includes('dekoracij')) {
      targetFolder = '01'; // Svadbene Dekoracije
    } else if (fileNameLower.includes('buket')) {
      targetFolder = '03'; // Buketi (including XL-XXXL buketi)
    } else if (fileNameLower.includes('xl')) {
      targetFolder = '02'; // XL buketi
    } else {
      // Distribute other images round-robin style across general categories
      targetFolder = CATEGORIES_TO_DISTRIBUTE[distributedIndex % CATEGORIES_TO_DISTRIBUTE.length];
      distributedIndex++;
    }

    const destDir = path.join(PUBLIC_DIR, targetFolder);
    const destPath = path.join(destDir, file);

    try {
      fs.renameSync(srcPath, destPath);
      console.log(`Moved: ${file} -> /public/${targetFolder}/${file}`);
    } catch (err) {
      console.error(`Error moving ${file}:`, err);
    }
  });

  // 2. Scan all subfolders 01 to 10 and map images to their respective category ID
  const finalImagesMap = {};
  
  // Initialize with empty arrays
  Object.values(CATEGORY_MAP).forEach(catId => {
    finalImagesMap[catId] = [];
  });

  Object.entries(CATEGORY_MAP).forEach(([folder, catId]) => {
    const folderPath = path.join(PUBLIC_DIR, folder);
    if (fs.existsSync(folderPath)) {
      const files = fs.readdirSync(folderPath);
      const imageExtensionsForFolders = ['.jpg', '.jpeg', '.png', '.heic', '.webp'];
      const images = files.filter(file => {
        const ext = path.extname(file).toLowerCase();
        return imageExtensionsForFolders.includes(ext) && file !== '.gitkeep';
      });

      // Map to browser-relative URLs (e.g. "/05/BOX1.jpg")
      finalImagesMap[catId] = images.map(file => `/${folder}/${file}`);
      console.log(`Category [${catId}] has ${images.length} images.`);
    }
  });

  // 3. Generate src/data/categoryImages.ts
  const dataDir = path.join(ROOT_DIR, 'src', 'data');
  ensureDir(dataDir);

  const fileContent = `// This file is auto-generated by scripts/sync-images.js. Do not edit manually.
export const categoryImages: Record<string, string[]> = ${JSON.stringify(finalImagesMap, null, 2)};
`;

  fs.writeFileSync(path.join(dataDir, 'categoryImages.ts'), fileContent, 'utf-8');
  console.log('Generated src/data/categoryImages.ts successfully!');
  console.log('--- Image sync complete ---');
}

sync();
