// This file is auto-generated by scripts/sync-images.js. Do not edit manually.
export const categoryImages: Record<string, string[]> = {
  "kinder": [],
  "svadbene": [],
  "xl-buketi": [],
  "buketi": [],
  "korpe": [],
  "box": [],
  "101-ruza": [],
  "rodjendani": [],
  "events": [],
  "slatki": []
};
